title: Research about Interactive Fault Localization
logo: /logo/logo_no-motto.png
show_downloads: false
google_analytics:

plugins:
  - jekyll-include-cache

markdown: kramdown

# theme: jekyll-theme-minimal
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.22.0"

search: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      author:
        name     : "University of Szeged, Department of Software Engineering"
        avatar   : "/logo/szte.png"
        location : "Szeged, Hungary"
        links:
        - label: "Official Website"
          icon: "fas fa-university"
          url: "https://www.sed.inf.u-szeged.hu/"
      toc: true
      toc_sticky: true
      sidebar:
        nav: "docs"
